name: OSCAL CI/CD
on:
  push:
    branches:
      - main
      - develop
      - "feature-*"
      - "release-*"
  pull_request:
    branches:
      - main
      - develop
      - "feature-*"
      - "release-*"
  workflow_dispatch:
jobs:
  checks:
    name: Status Checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version-file: "build/.nvmrc"
          cache: "npm"
          cache-dependency-path: "build/package-lock.json"
      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils
      - name: Read node version from `.nvmrc` file
        id: nvmrc
        shell: bash
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
      - name: Install required node.js version
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: |
          make configure
        working-directory: build
      - name: Run all pipelines
        run: |
          make --keep-going build
        working-directory: build
